### ISSUE TITLE
FC when changing orientation on load screen

### ISSUE THREAD

**Issue by GoogleCodeExporter** [alistairreilly/andors-trail#164]
```
From forum:
http://andors.techby2guys.com/viewtopic.php?p=262#p262


If I switch the direction of the phone when it's loading a savegame it crashes.

```

Original issue reported on code.google.com by `oskar.wi...@gmail.com` on 24 Feb 2011 at 10:00

**Comment by GoogleCodeExporter** [comment]
```
Need more info, doesn't happen to me on 2.2 when loading from quick save, 
normal save, or starting a new game.  OS version and device would be helpful.
```

Original comment by `sdeva...@gmail.com` on 24 Feb 2011 at 11:45

**Comment by GoogleCodeExporter** [comment]
```
Android 2.2 on a wildfire here. (Happens still in latest version.)
It happens while loading a game from menu. (load saved game)

I send an automatic bug report with comment: "issue 164"
Does not happen always, most of the time it does not happen.
```

Original comment by `SamuelPl...@gmail.com` on 26 Feb 2011 at 8:42

**Comment by GoogleCodeExporter** [comment]
```
Thanks Samuel, your report contains the following info:

v0.6.7, v0.6.8
Feb 27, 2011 7:15:32 PM
3
7 reports 
java.lang.NullPointerException
    at com.gpl.rpg.AndorsTrail.WorldSetup$2.onPostExecute(WorldSetup.java:91)
    at com.gpl.rpg.AndorsTrail.WorldSetup$2.onPostExecute(WorldSetup.java:1)
    at android.os.AsyncTask.finish(AsyncTask.java:417)
    at android.os.AsyncTask.access$300(AsyncTask.java:127)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:429)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:143)
    at android.app.ActivityThread.main(ActivityThread.java:4914)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:521)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    at dalvik.system.NativeStart.main(Native Method)

This should make it easier to find the bug.
```

Original comment by `oskar.wi...@gmail.com` on 28 Feb 2011 at 4:43
